version: 2.1

jobs:
  test: &test
    parallelism: 1
    parameters:
      ruby-version: { type: string }
    docker:
      - image: ruby:<<parameters.ruby-version>>
    steps:
      - checkout
      - run: bundle install
  publish: &publish
    docker:
      - image: ruby:2.6
    steps:
      - checkout
      - run: |
          echo ${RUBYGEM_PUBLISH_API_KEY}
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: $RUBYGEMS_PUBLISH_API_KEY\n" > $HOME/.gem/credentials
          gem build *.gemspec
          cat $HOME/.gem/credentials
          gem push *.gem
workflows:
  version: 2
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["3.0"]
      - publish:
          requires:
            - test
